### ISSUE TITLE
Why buffer example is not working

### ISSUE THREAD

**Issue by raghadalhelal** [h2non/filetype.py#102]
```
$ python buffer.py 
Traceback (most recent call last):
  File "buffer.py", line 23, in <module>
    main()
  File "buffer.py", line 13, in main
    kind = filetype.guess(data)
  File "/home/myuser/.local/lib/python2.7/site-packages/filetype/filetype.py", line 28, in guess
    return match(obj) if obj else None
  File "/home/myuser/.local/lib/python2.7/site-packages/filetype/match.py", line 28, in match
    buf = get_bytes(obj)
  File "/home/myuser/.local/lib/python2.7/site-packages/filetype/utils.py", line 64, in get_bytes
    return get_signature_bytes(obj)
  File "/home/myuser/.local/lib/python2.7/site-packages/filetype/utils.py", line 17, in get_signature_bytes
    with open(path, 'rb') as fp:
IOError: [Errno 2] No such file or directory: 'HelloWorld\n'
```

I tried to use buffer.py on a text file but without success.

**Comment by dosas** [comment]
The end of life for python 2.7 was one year ago and the deprecation timeline probably two years or longer. So I don't think that anybody will care to fix it ... 

Have you tried python 3.8:
```
$ pip install filetype
$ python examples/buffer.py 
File extension: jpg
File MIME type: image/jpeg
```
