### ISSUE TITLE
AttributeError: 'function' object has no attribute 'archive'

### ISSUE THREAD

**Issue by fili** [h2non/filetype.py#60]
FYI
```
import filetype
import gzip

>>> filetype.helpers.is_archive(gzip.compress(b'test'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/filetype/helpers.py", line 74, in is_archive
    return match.archive(obj) is not None
AttributeError: 'function' object has no attribute 'archive'
```
Seems there is a naming conflict when using helpers directly with the filetype.match.match and filetype.match.archive

Going around the helpers works though:

```
import gzip
from filetype.match import archive

>>> bool(archive(gzip.compress(b'test')))
True
```

**Comment by DanielSwain** [comment]
I can confirm this problem:

```
from filetype import helpers
helpers.is_audio('/path/to/file.txt')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/virtualenvs/venv/lib/python3.6/site-packages/filetype/helpers.py", line 90, in is_audio
    return match.audio(obj) is not None
AttributeError: 'function' object has no attribute 'audio'
```

**Comment by DanielSwain** [comment]
@h2non Reminder to close this issue
