### ISSUE TITLE
pip could not install 

### ISSUE THREAD

**Issue by acgmohu** [h2non/filetype.py#8]
```
λ pip install filetype
Collecting filetype
  Using cached filetype-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\LOCAL_TEMP\pip-build-605g52_c\filetype\setup.py", line 16, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "C:\Anaconda3\lib\codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\LOCAL_TEMP\\pip-build-605g52_c\\filetype\\README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in D:\LOCAL_TEMP\pip-build-605g52_c\filetype\
```

I could install by source, pip could not work.

**Comment by h2non** [comment]
Fixed. Try it again: `pip install filetype --upgrade`

Thanks for reporting.

**Comment by acgmohu** [comment]
Ths. :+1: 

It works.
